name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t learndotnet78/dockerapi:latest -f Docker.API/Dockerfile .
    - name: Push the Docker image
      run: docker push learndotnet78/dockerapi:latest
